// Generated by Wrangler on Mon Oct 14 2024 18:57:01 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_REDIRECT_URI: string;
	GITHUB_ACCOUNT_ID: string;
	DB: D1Database;
}
