name = "surajtc-dev"
compatibility_date = "2024-10-11"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "surajtc-dev-db"
database_id = "196008ab-72c4-443f-aa38-94167ffa5058"
migrations_dir = "app/drizzle/migrations"